# Generated by Django 4.1.2 on 2024-07-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_platillo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcontacto',
            name='celular',
            field=models.IntegerField(blank=True),
        ),
    ]
